version: '3.1'
services:
  stats-server:
    build: stat
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/stat

  stats-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore

