CREATE TABLE IF NOT EXISTS stat
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY not null
        CONSTRAINT stat_pk
            PRIMARY KEY,
    app       varchar,
    uri       varchar,
    ip        varchar,
    timestamp timestamp
);